import type { Metadata } from "next";
import "react-loading-skeleton/dist/skeleton.css";
import "../styles/main.scss";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="">
      <body>
        <Header />
        <main className="container mx-auto relative px-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
